services:
  app:
    build: ./app-reservas
    container_name: app_reservas
    env_file: .env
    environment:
      # Asegúrate que tu Next use esta URL para el backend real (externo o en otra máquina)
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE}
    ports:
      - "3000:3000"
    restart: unless-stopped

  # Opcional: túnel para exponer el front
  cloudflared:
    image: cloudflare/cloudflared:2025.2.0
    container_name: cloudflared_tunnel
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TOKEN}
    depends_on:
      app:
        condition: service_started
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}